apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: universe
resources:
  - ../../../crds
  - namespace.yaml
  - minio.yaml
  - operator.yaml
  - networkpolicy-agent-deny-egress.yaml
  - networkpolicy-agent-allow-egress.yaml
  - networkpolicy-sandbox-deny-egress.yaml
  - gvisor-runtimeclass.yaml
