apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-sandbox-shell
  namespace: universe
spec:
  podSelector:
    matchLabels:
      app: sandbox-shell
  policyTypes:
    - Egress
  egress: []
