{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rynxs.fullname" . }}-operator
  labels:
    {{- include "rynxs.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rynxs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rynxs.fullname" . }}-operator
{{- end -}}
