{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "rynxs.operator.labels" . | nindent 4 }}
{{- end }}
