apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - universe.ai_agents.yaml
  - universe.ai_sessions.yaml
  - universe.ai_universes.yaml
  - universe.ai_tasks.yaml
  - universe.ai_teams.yaml
  - universe.ai_metrics.yaml
  - universe.ai_messages.yaml
